export enum ProductCategories {
    Beauty = 'beauty',
    Fragrances = 'fragrances',
    Furniture = 'furniture',
    Groceries = 'groceries',
    HomeDecoration = 'home-decoration',
    KitchenAccessories = 'kitchen-accessories',
    Laptops = 'laptops',
    MenShirts = 'men-shirts',
    MenShoes = 'men-shoes',
    MensWatches = 'mens-watches',
    MobileAccessories = 'mobile-accesories',
    Motorcycle = 'motorcycle',
    SkinCare = 'skin-care',
    SmartPhones = 'smartphones',
    SportAccessories = 'sport-accessories',
    Sunglasses = 'sunglasses',
    Tablets = 'tablets',
    Tops = 'tops',
    Vehicle = 'vehicle',
    WomensBags = 'womens-bags',
    WomensJewellery = 'womens-jewellery',
    WomensShoes = 'womens-shoes',
    WomensWatches = 'womens-watches'
}